// Public sample families for the "Explore" page
// These simulate publicly shared family archives

import type { Family, Memory, FamilyMember, TimelineEvent, Chapter } from './store';

export const PUBLIC_FAMILIES = [
  {
    id: 'pub-001',
    name: 'The Mehta Family',
    tagline: 'From Gujarat to the world — three generations of artisans and engineers.',
    location: 'Ahmedabad → Mumbai → Toronto',
    years: '1938 — Present',
    memberCount: 14,
    memoryCount: 23,
    coverGradient: 'linear-gradient(135deg, #fef3e2 0%, #fde8c8 100%)',
    accentColor: '#d97706',
    featuredMemory: 'The Workshop at Raipur Gate',
    featuredYear: 1958,
    isPublic: true,
    ownerId: 'pub-user-1',
    memberIds: [],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'pub-002',
    name: 'The Krishnan Family',
    tagline: 'A century of music, medicine, and migration.',
    location: 'Madurai → Chennai → London',
    years: '1920 — Present',
    memberCount: 18,
    memoryCount: 41,
    coverGradient: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    accentColor: '#2e6b4f',
    featuredMemory: 'Learning the Veena at Sunrise',
    featuredYear: 1945,
    isPublic: true,
    ownerId: 'pub-user-2',
    memberIds: [],
    createdAt: '2024-02-10T00:00:00Z',
  },
  {
    id: 'pub-003',
    name: 'The Singh Family',
    tagline: 'From the fields of Punjab to the courts of law.',
    location: 'Ludhiana → Delhi → New York',
    years: '1930 — Present',
    memberCount: 22,
    memoryCount: 36,
    coverGradient: 'linear-gradient(135deg, #fef2f2 0%, #ffe4e6 100%)',
    accentColor: '#be4a3a',
    featuredMemory: 'The Partition Journey',
    featuredYear: 1947,
    isPublic: true,
    ownerId: 'pub-user-3',
    memberIds: [],
    createdAt: '2024-03-05T00:00:00Z',
  },
  {
    id: 'pub-004',
    name: 'The Iyer Family',
    tagline: 'Scholars, cooks, and storytellers since 1890.',
    location: 'Thanjavur → Bangalore → Singapore',
    years: '1890 — Present',
    memberCount: 29,
    memoryCount: 58,
    coverGradient: 'linear-gradient(135deg, #eef0fc 0%, #e0e7ff 100%)',
    accentColor: '#3b4fa8',
    featuredMemory: 'The First Library Visit',
    featuredYear: 1932,
    isPublic: true,
    ownerId: 'pub-user-4',
    memberIds: [],
    createdAt: '2024-01-28T00:00:00Z',
  },
  {
    id: 'pub-005',
    name: 'The Nair Family',
    tagline: 'Artists and architects who built a city.',
    location: 'Thiruvananthapuram → Kochi → Melbourne',
    years: '1905 — Present',
    memberCount: 16,
    memoryCount: 28,
    coverGradient: 'linear-gradient(135deg, #fff8e6 0%, #fef3c7 100%)',
    accentColor: '#d97706',
    featuredMemory: 'The House on the Hill',
    featuredYear: 1962,
    isPublic: true,
    ownerId: 'pub-user-5',
    memberIds: [],
    createdAt: '2024-04-12T00:00:00Z',
  },
  {
    id: 'pub-006',
    name: 'The Patel Family',
    tagline: 'Farmers who became technologists. Roots in Anand.',
    location: 'Anand → Surat → San Francisco',
    years: '1925 — Present',
    memberCount: 31,
    memoryCount: 44,
    coverGradient: 'linear-gradient(135deg, #f0fdf4 0%, #d1fae5 100%)',
    accentColor: '#2e6b4f',
    featuredMemory: 'The First Telephone',
    featuredYear: 1972,
    isPublic: true,
    ownerId: 'pub-user-6',
    memberIds: [],
    createdAt: '2024-02-20T00:00:00Z',
  },
];

export const RELATIONSHIP_OPTIONS = [
  'Self', 'Father', 'Mother', 'Son', 'Daughter', 'Brother', 'Sister',
  'Grandfather (Paternal)', 'Grandmother (Paternal)',
  'Grandfather (Maternal)', 'Grandmother (Maternal)',
  'Uncle', 'Aunt', 'Nephew', 'Niece', 'Cousin',
  'Husband', 'Wife', 'Partner',
  'Father-in-law', 'Mother-in-law',
  'Step-father', 'Step-mother', 'Step-sibling',
  'Great-grandfather', 'Great-grandmother',
  'Family Friend', 'Mentor', 'Other',
];

export const EMOTION_OPTIONS = [
  'Joy', 'Wonder', 'Pride', 'Love', 'Gratitude', 'Nostalgia', 'Peace',
  'Belonging', 'Hope', 'Courage', 'Resilience', 'Grief', 'Loss',
  'Longing', 'Fear', 'Uncertainty', 'Surprise', 'Transformation',
];

export const MEMORY_TAGS = [
  'Childhood', 'Food', 'Music', 'Education', 'Work', 'Travel',
  'Migration', 'War & Peace', 'Festivals', 'Home', 'Love & Marriage',
  'Birth', 'Loss', 'Reunion', 'First Time', 'Tradition', 'Humour',
  'Struggle', 'Achievement', 'Nature', 'Faith', 'Community',
];

export const INTERVIEW_QUESTIONS = [
  "Tell me about the house where you grew up. What do you remember most about it?",
  "What sounds, smells or tastes take you immediately back to your childhood?",
  "Who was the most important person in shaping who you became? Tell me about them.",
  "Was there a moment when you felt your life truly changed direction?",
  "What is a tradition in your family that you hope will never be forgotten?",
  "Tell me about a journey — physical or emotional — that defined you.",
  "What was the hardest thing you ever had to do? How did you find the strength?",
  "Describe a meal that carries a whole story inside it.",
  "What do you most want the next generation to know about your life?",
  "Is there something you never said to someone you loved? You can say it now.",
  "Tell me about an ordinary Tuesday in your childhood — nothing special. Just a day.",
  "What object from your past do you still think about? What does it mean to you?",
];
